add npm package, add true sync
xmoonlight/includeHTML pull request #7
Opened 2016-09-14 13:30 UTC by lgg

fix #1 #2

2016-09-16 00:39 UTC, xmoonlight commented on includeHTML.js
> + USAGE:
Нужно поправить USAGE.

2016-09-16 00:48 UTC, xmoonlight commented on includeHTML.js
> +    function includeSrc(src, destination, callback) {
Здесь нужно оставить прежнюю инициализацию, а синхронизацию вставить внутрь!

2016-09-16 00:49 UTC, xmoonlight commented on includeHTML.js
> +    function includeHTML(src, destination, callback) {
Убрать функцию, а тело кода - внести в мою функцию includeHTML.

2016-09-17 01:44 UTC, xmoonlight requested changes
Требуются указанные исправления.

2016-09-18 23:25 UTC, xmoonlight commented
@lgg я обновил пару файлов и еще плюс необходимые правки, поэтому сделаем так:
этот - я закрываю, а ты после правок всех моих замечаний - создай новый PullRequest.

2016-09-18 23:25 UTC, closed without merging

2016-09-28 08:14 UTC, xmoonlight commented
@lgg повторный запрос на PullRequest по актуальным файлам с учётом исправлений -  сделаешь?

2016-09-28 22:17 UTC, lgg commented
@xmoonlight да, но чуть позже.
Про USAGE правки понял, а остальное нет. Можешь пояснить подробнее?

2016-09-29 09:08 UTC, xmoonlight commented
@lgg Не плоди функции.
Функционал перебора по массиву - запихни в существующую includeHTML() и внутри проверку поставь на 1-ый параметр: если - массив, то твой код (true-sync) и рекурсивный вызов, иначе - мой.
Т.е., нужно сделать "перегрузку" функции innerHTML() и рекурсию в ней же (для true-sync), чтобы оставалась всегда ОДНА функция для пользования.